language: node_js
node_js:
  - "stable"
sudo: false
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - "pnpm install"
script:
  - "pnpm test"
after_success:
  - 'pnpm coveralls'
